### ISSUE TITLE
Ceci n'est pas un issue

### ISSUE THREAD

**Issue by BlakvGhost** [femi-Zedev/file_upload#1]
Salut, je crois que ça sera plus cool si c'était développer comme une librairie indépendante qu'on pourrait implémenter dans son projet (Ex: `Dropzone.js`), parce que là c'est juste un projet complet, son implémentation consisterait à une lourde tâche.

**Comment by femi-Zedev** [comment]
Hello merci pour le feed back. Je pense que serait un peu difficile d'encapsuler toute la logique de l'upload dans une librairie parce que les besoins et le comportement qu'on peut vouloir sera différent d'un projet à un autre. Mais je suis quand même ouvert à l'idée de cogiter et d'aboutir sur une lib qui simplifie un temps soit peu le process
